### ISSUE TITLE
Run job doesn't show output if there are any warnings

### ISSUE THREAD

**Issue by crumblingstatue** [Canop/bacon#81] opened 2022-05-19 09:17 UTC
```Rust
fn main() {
	println!("Hello world!");
}
```
```
 playground   run   pass!

   Compiling playground v0.1.0 (/tmp/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target/debug/playground`
Hello world!
```
```Rust
fn main() {
	let unused = 42;
	println!("Hello world!");
}
```

```
 playground   run    1 warning

 1  warning: unused variable: `unused`
  --> src/main.rs:2:6
   |
 2 |     let unused = 42;
   |         ^^^^^^ help: if this is intentional, prefix it with an underscore: `_unused`
   |
   = note: `#[warn(unused_variables)]` on by default
```

`Hello World!` isn't shown in the second case.

**Comment by MarcoBuster** [comment] 2022-07-29 12:56
Any updates?

**Comment by Canop** [comment] 2022-07-29 13:36
> Any updates?

I had just forgotten this issue, sorry.

**Comment by Canop** [comment] 2022-07-29 18:33
This should be fixed on branch fix-issue-81 : the job takes a new "allow_warnings" setting.

More tests are needed before I merge into main. I'd appreciate your tests.

**Comment by jjmarchewitz** [comment] 2022-08-12 17:13
Hi! I'm new to the rust game and I've been using bacon to work on my first project. I'm also experiencing this issue and switching to the branch `fix-issue-81` fixed it for me! It worked both with the default .toml file and with a project-specific bacon.toml file. I cloned and built Bacon for release from within a common `repos` folder and then executed it with `../bacon/target/release/bacon`. Worked perfectly!

**Comment by crumblingstatue** [comment] 2022-08-13 13:38
I tried the branch with the example given above, but it doesn't print hello world.
```
warning: unused variable: `unused`                                                                                                                                                            ▐
 --> src/main.rs:2:6                                                                                                                                                                          ▐
  |                                                                                                                                                                                           ▐
2 |     let unused = 42;                                                                                                                                                                      ▐
  |         ^^^^^^ help: if this is intentional, prefix it with an underscore: `_unused`                                                                                                      ▐
  |                                                                                                                                                                                           ▐
  = note: `#[warn(unused_variables)]` on by default                                                                                                                                           ▐
                                                                                                                                                                                              ▐
warning: `loltest` (bin "loltest") generated 1 warning                                                                                                                                        ▐
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s                                                                                                                                 ▐
     Running `target/debug/loltest`
```

**Comment by crumblingstatue** [comment] 2022-08-13 13:42
It would also be nice if there was an option to scroll to the end automatically on every update.
It would be useful when doing iterative development that's based on program output.

**Comment by crumblingstatue** [comment] 2022-08-13 13:51
It also seems non-zero exit code inhibits output as well.
Seeing panic/crash output is very important. Otherwise, users are forced to leave bacon and rerun to see panic output.

**Comment by jjmarchewitz** [comment] 2022-08-13 16:34
Now that you mention it, the last line is being swallowed for me too. I didn't notice because my code has a ton of output

**Comment by Canop** [comment] 2022-08-28 07:03
Hum. I can't reproduce the last line being swallowed :\
![image](https://user-images.githubusercontent.com/617006/187061840-da2010f2-7665-4703-a01c-78a154e699e4.png)
There are sometimes synchronization problem since the switch to tokio so that might be another occurence.

**Comment by Canop** [comment] 2022-08-28 07:49
I also have the panic:
![image](https://user-images.githubusercontent.com/617006/187063762-46902afe-341b-424a-b6e3-e161564c3f9d.png)

I'll merge this and we'll create other issues for the last line being swallowed if confirmed.

**Closed** 2022-08-28 09:21 UTC
