### ISSUE TITLE
No wrap or summary mode on Windows

### ISSUE THREAD

**Issue by kiba-2020** [Canop/bacon#73] opened 2022-02-28 10:07 UTC
If bacon is started on Windows wrapping and summary mode do not work. The -w parameter is without effect and there is no text at the bottom telling you to press w to wrap lines or s for summary mode like when using Linux.

![grafik](https://user-images.githubusercontent.com/71230252/155964344-7b80e2e8-b0a8-4408-99b8-f0ddbf80dc9a.png)

**Comment by Canop** [comment] 2022-02-28 10:17
It's a duplicate of #70 

In short: on some Windows terminals, TTY escape commands seem to be lost of changed which prevents bacon from correctly parsing them.

I'll try to fix that but it's hard for me without any proper windows computer.

**Closed** 2022-02-28 10:17 UTC

**Comment by Elarcis** [comment] 2022-07-17 23:09
I have this issue as well, I’m using VSCode’s integrated terminal.

It only seems to arise when using Powershell though, as if I start a WSL terminal, I get proper warnings.

Powershell is on the left, Debian (WSL) on the right:
![image](https://user-images.githubusercontent.com/990841/179428467-0fe72b64-894c-47b0-91ac-746fe158ac23.png)

Trying to enable summary mode gives this:
![image](https://user-images.githubusercontent.com/990841/179428496-560ba267-2b5e-4922-8b97-a33cec357a8a.png)

**Comment by Canop** [comment] 2022-07-18 09:22
@kiba-2020 Thanks for the report. As I don't have a Windows computer, I'm never sure of whether it really works on Windows
